[UI]
enableRichToolTips = true

[HTTPServer]
enabled = true
addr = "localhost"
port = 12321
useIpv6 = true

[GHub]
enabled = true

[Native]
enabled = true

# Time in seconds to retry a device poll on failure
retryTime = 10

# Time in seconds to next device poll on sucess
pollPeriod = 600

# List of disabled devices
disabledDevices = [
]