name: Nightly Builds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8

    - uses: actions/setup-python@v5 
      with:
        python-version: '3.11' 

    - name: python .\publish.py
      run: |
        $commit_ts=git show --no-patch --format=%at
        $commit_ds=(([System.DateTimeOffset]::FromUnixTimeSeconds($commit_ts)).DateTime).ToString("yyyyMMdd")
        python .\publish.py --version-suffix="-nightly+$commit_ds"

    - name: upload nightly build
      env:
        GH_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
      run: |
        $commit_ts=git show --no-patch --format=%at
        $commit_ds=(([System.DateTimeOffset]::FromUnixTimeSeconds($commit_ts)).DateTime).ToString("yyyyMMdd")
        gh release create -R "andyvorld/LGSTrayBattery-nightly" `
          $commit_ds `
          (get-item ./bin/Release/publish/*.zip)